name: Build Project and Publish to itch.io
on:
  workflow_dispatch:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
      
jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    concurrency: 
      group: unity-build
      cancel-in-progress: true
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true
    - uses: actions/cache@v4
      with:
        path: Library
        key: Library
    - name: Build project
      uses: game-ci/unity-builder@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        targetPlatform: WebGL
        allowDirtyBuild: true # should not leave here, but plastic scm does not work well with git lfs
    - uses: buildalon/setup-butler@v1
      with:
        api-key: ${{ secrets.BUTLER_CREDENTIALS  }}
    - name: Upload to itch.io
      run: butler push build/WebGL robscatch/test-project:html5
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS  }}
